# pyproject.toml
[project]
name = "Photopea-Sidebar"
description = "A custom extension for ComfyUI that integrates Photopea directly into the sidebar."
version = "1.0.0"
license = { file = "LICENSE.txt" }
dependencies  = []

[project.urls]
Repository = "https://github.com/nolbert82/ComfyUI-Photopea-Sidebar"

[tool.comfy]
PublisherId = "nolbert82"
DisplayName = "Photopea Sidebar"
Icon = "./icon.png"